"use client";
import { useEffect, useRef, useState } from "react";
import { audiobookFetch, audiobookCloud, uploadAudiobook, reuseAudiobook, type Operation } from "@/lib/audiobook-client";
import { wavOverview, type Overview } from "@/lib/audiobook-wave";
import { defaultMasterStem, masterFilename } from "@/lib/audiobook-filename";
import "./audiobook.css";
type Slot = "before" | "after";
type Track = Overview & {url:string};
type Analysis = Parameters<typeof import("../local-run/LocalRunPanel").evaluateSpecRows>[1];
type CloudTrack = Track & {analysis:Analysis;noiseFloorDb:number|null};
type Media = {before:CloudTrack;after?:CloudTrack};
type Result = {target:number;lufs:number;peak:number};
type Row = {parameter:string;before:string;after:string;requirement:string;status:string;outcome?:string};
type Job = {id:string;name:string;target:number;started:number;operation:Operation;overview?:Overview;sourceId?:string;expires?:number};
const KEY="saltwaves-audiobook-preview-job";
const endpoint=(id:string,kind="status")=>`/api/audiobook?id=${id}&kind=${kind}`;
const fmt=(s:number)=>{const n=Math.max(0,Math.floor(Number.isFinite(s)?s:0));return `${Math.floor(n/3600)}:${String(Math.floor(n/60)%60).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;};
function remember(job:Job|null){try{if(job)localStorage.setItem(KEY,JSON.stringify(job));else localStorage.removeItem(KEY);}catch{/* Optional recovery storage. */}}
async function localTrack(file:File):Promise<Track>{
  const overview=await wavOverview(file);
  if(overview)return {...overview,url:URL.createObjectURL(file)};
  if(file.size>200*1024*1024)throw new Error("För stora filer: välj WAV i mono eller stereo, 16 eller 24 bitar. Mindre MP3, M4A och AIFF stöds också.");
  const ctx=new OfflineAudioContext(1,1,8000),buffer=await ctx.decodeAudioData(await file.arrayBuffer());
  if(buffer.duration>54000)throw new Error("Filen får vara högst 15 timmar.");
  const samples=buffer.getChannelData(0);let energy=0;
  const peaks=Array.from({length:2000},(_,i)=>{let peak=0;for(let n=Math.floor(i*samples.length/2000);n<Math.floor((i+1)*samples.length/2000);n++){peak=Math.max(peak,Math.abs(samples[n]));energy+=samples[n]*samples[n];}return peak;});
  return {url:URL.createObjectURL(file),duration:buffer.duration,peaks,rms:Math.sqrt(energy/samples.length)};
}
function Wave({item,current,title,onSeek,selection}:{item:Overview|null;current:number;title:string;onSeek:(t:number)=>void;selection?:{start:number;length:number;disabled:boolean;change:(t:number)=>void}}){
  const box=useRef<HTMLDivElement>(null),drag=useRef<{x:number;start:number}|null>(null);
  const duration=item?.duration||1,scale=Math.max(.01,...(item?.peaks||[]));
  return <div className="ab-wave is-active"><div className="ab-wave-label"><span>{title}</span><span>{item?fmt(item.duration):"Väntar på resultat"}</span></div><div className="ab-wave-body" ref={box}>
    {item?<><svg viewBox="0 0 2000 100" preserveAspectRatio="none" aria-hidden="true">{item.peaks.map((p,i)=><line key={i} x1={i*2000/item.peaks.length} x2={i*2000/item.peaks.length} y1={50-p/scale*44} y2={50+p/scale*44} stroke="currentColor" strokeWidth="1"/>)}</svg><input aria-label={`Spelposition ${title}`} type="range" min={0} max={duration} step={.1} value={Math.min(current,duration)} onChange={e=>onSeek(Number(e.target.value))}/><div className="ab-playhead" style={{left:`${Math.min(100,current/duration*100)}%`}}/>
    {selection&&<div className="ab-selection" role="slider" aria-label="Välj ett utdrag" aria-valuemin={0} aria-valuemax={Math.max(0,duration-selection.length)} aria-valuenow={selection.start} aria-valuetext={`${fmt(selection.start)} till ${fmt(Math.min(duration,selection.start+selection.length))}`} aria-disabled={selection.disabled} tabIndex={selection.disabled?-1:0} style={{left:`${selection.start/duration*100}%`,width:`${Math.min(selection.length,duration)/duration*100}%`}}
      onPointerDown={e=>{if(selection.disabled)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,start:selection.start};}}
      onPointerMove={e=>{if(!drag.current||!box.current)return;selection.change(drag.current.start+(e.clientX-drag.current.x)/box.current.clientWidth*duration);}}
      onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}
      onKeyDown={e=>{if(selection.disabled)return;const move=e.shiftKey?60:10;if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();selection.change(selection.start+(e.key==="ArrowLeft"?-move:move));}if(e.key==="Home"){e.preventDefault();selection.change(0);}if(e.key==="End"){e.preventDefault();selection.change(duration-selection.length);}}}><span>↔</span></div>}
    </>:<div className="ab-wave-empty">Välj en ljudfil för att börja</div>}
  </div></div>;
}
export default function AudiobookStudio(){
  const [file,setFile]=useState<File|null>(null),[source,setSource]=useState<Track|null>(null),[overview,setOverview]=useState<Overview|null>(null);
  const [downloadStem,setDownloadStem]=useState("");
  const [name,setName]=useState(""),[target,setTarget]=useState(-18),[job,setJob]=useState<Job|null>(null),[sourceId,setSourceId]=useState<string|null>(null);
  const [phase,setPhase]=useState("idle"),[message,setMessage]=useState(""),[error,setError]=useState(""),[media,setMedia]=useState<Media|null>(null),[result,setResult]=useState<Result|null>(null),[rows,setRows]=useState<Row[]>([]);
  const [start,setStart]=useState(0),[length,setLength]=useState(300),[whole,setWhole]=useState(true),[matched,setMatched]=useState(true),[slot,setSlot]=useState<Slot>("before"),[playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[reportBusy,setReportBusy]=useState(false);
  const a=useRef<HTMLAudioElement>(null),b=useRef<HTMLAudioElement>(null),input=useRef<HTMLInputElement>(null),context=useRef<AudioContext|null>(null),gains=useRef<GainNode[]>([]),active=useRef<Slot>("before"),urls=useRef<string[]>([]),pendingSeek=useRef<number|null>(null);
  const submission=useRef<{signature:string;key:string}|null>(null);
  const busy=["loading","uploading","running"].includes(phase),before=whole?source:media?.before,after=whole?null:media?.after;
  const synced=!!before&&!!after&&Math.abs(before.duration-after.duration)<.2;
  const comparisonOffset=job?.operation?.mode==="preview"?job.operation.start:0;
  const stale=job?.operation?.mode==="preview"&&(Math.abs(job.operation.start-start)>.05||job.operation.duration!==length||job.target!==target);
  function stop(reset=false){a.current?.pause();b.current?.pause();setPlaying(false);if(reset)seek(0);}
  function seek(time:number){for(const el of [a.current,b.current])if(el?.src&&Number.isFinite(el.duration))el.currentTime=Math.min(time,el.duration);setCurrent(time);}
  function move(value:number){setStart(Math.round(Math.max(0,Math.min(value,Math.max(0,(overview?.duration||0)-length)))*10)/10);}
  function mix(next:Slot,matching=matched){active.current=next;setSlot(next);const ctx=context.current;gains.current.forEach((gain,i)=>{if(!ctx)return;const t=ctx.currentTime;gain.gain.cancelScheduledValues(t);gain.gain.setValueAtTime(gain.gain.value,t);const ratio=matching&&before&&after?Math.min(1,i===0?after.rms/before.rms:before.rms/after.rms):1;gain.gain.linearRampToValueAtTime(i===(next==="before"?0:1)?(Number.isFinite(ratio)?ratio:1):0,t+.02);});}
  async function play(){if(playing){stop();return;}try{if(!context.current){const ctx=new AudioContext();context.current=ctx;gains.current=[a.current!,b.current!].map(el=>{const gain=ctx.createGain();ctx.createMediaElementSource(el).connect(gain).connect(ctx.destination);return gain;});}await context.current.resume();mix(active.current);if(synced&&a.current&&b.current){b.current.currentTime=a.current.currentTime;await Promise.all([a.current.play(),b.current.play()]);}else await a.current?.play();setPlaying(true);setError("");}catch{stop();setError("Ljudet kunde inte spelas. Tryck på Play igen eller välj ett provavsnitt.");}}
  function listenWhole(time=0){stop();mix("before");if(whole)seek(time);else{pendingSeek.current=time;setWhole(true);setCurrent(time);}}
  function listenComparison(){stop();mix("before");pendingSeek.current=0;setWhole(false);setCurrent(0);}
  async function choose(next:File){if(busy)return;stop(true);setError("");remember(null);setJob(null);setMedia(null);setRows([]);setResult(null);setSourceId(null);setSource(null);setOverview(null);setFile(null);setName(next.name);setStart(0);setWhole(true);mix("before");submission.current=null;urls.current.forEach(URL.revokeObjectURL);urls.current=[];
    if(!/\.(wav|mp3|m4a|aiff)$/i.test(next.name)||next.size>6*1024**3){setPhase("idle");setError("Välj WAV, MP3, M4A eller AIFF, högst 6 GB.");return;}
    setPhase("loading");setMessage("Läser in vågformen…");try{const item=await localTrack(next);urls.current.push(item.url);setSource(item);setOverview(item);setFile(next);setPhase("ready");}catch(e){setPhase("idle");setError(e instanceof Error?e.message:"Filen kunde inte läsas.");}}
  async function run(mode:Operation["mode"]){if(busy||(!file&&!sourceId))return;
    const operation:Operation={mode,start:mode==="preview"?start:0,duration:mode==="preview"?length:300};
    const signature=JSON.stringify([sourceId,file?.name,file?.size,file?.lastModified,target,operation]);if(submission.current?.signature!==signature)submission.current={signature,key:crypto.randomUUID()};
    stop();mix("before");setError("");setPhase("uploading");setMessage(sourceId?"Startar körningen med din uppladdade fil…":"Förbereder uppladdningen…");
    try{let data:{id:string};if(sourceId)data=await reuseAudiobook(sourceId,target,submission.current.key,operation);
      else if(await audiobookCloud()){const began=performance.now();let initial:number|null=null;data=await uploadAudiobook(file!,target,submission.current.key,(bytes,total)=>{if(initial===null)initial=bytes;const seconds=(performance.now()-began)/1000,speed=seconds>1?(bytes-initial)/seconds:0;setMessage(`Laddar upp ${Math.floor(bytes/total*100)} % · ${(bytes/1024**2).toFixed(0)} av ${(total/1024**2).toFixed(0)} MB${speed>0?` · ${(speed/1024**2).toFixed(1)} MB/s · cirka ${fmt((total-bytes)/speed)} kvar`:""}`);},operation);}
      else{throw new Error("Provmastring och leveranskontroll körs på den inloggade testsidan. Öppna app.saltwaves.studio/tools/audiobook.");}
      const next:Job={id:data.id,name,target,started:Date.now(),operation,overview:overview?{peaks:overview.peaks,duration:overview.duration,rms:overview.rms}:undefined,sourceId:sourceId||data.id};
      setDownloadStem(defaultMasterStem(next.name,mode==="preview"));setJob(next);remember(next);setMedia(null);setRows([]);setResult(null);setWhole(true);setPhase("running");submission.current=null;
    }catch(e){setPhase("ready");setError(e instanceof Error?e.message:"Körningen kunde inte startas.");}}
  useEffect(()=>{let cancelled=false;void Promise.resolve().then(()=>{if(cancelled)return;try{const saved=JSON.parse(localStorage.getItem(KEY)||"null") as Job|null;if(saved&&/^[a-f0-9]{32}$/.test(saved.id)&&[-19,-18,-17,-16].includes(saved.target)){saved.operation ||= {mode:"master",start:0,duration:300};setJob(saved);setDownloadStem(defaultMasterStem(saved.name,saved.operation.mode==="preview"));setName(saved.name);setTarget(saved.target);setOverview(saved.overview||null);setStart(saved.operation.start);setLength(saved.operation.duration);setPhase("running");}}catch{remember(null);}});return()=>{cancelled=true;urls.current.forEach(URL.revokeObjectURL);void context.current?.close();};},[]);
  useEffect(()=>{if(!job||phase!=="running")return;let cancelled=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const response=await audiobookFetch(endpoint(job.id),{signal:AbortSignal.timeout(30000)});const data=await response.json();if(cancelled)return;
    if(!response.ok){if([401,403,404,410].includes(response.status)){setPhase("error");setError(data.error);if([404,410].includes(response.status)){remember(null);setSourceId(null);}return;}throw new Error(data.error);}
    if(data.status==="error"||data.status==="expired"){setPhase("error");setError(data.error||"Filens 48 timmar har löpt ut.");if(data.status==="error")setSourceId(data.sourceId||job.sourceId||job.id);return;}
    if(data.status==="done"){
      if(!data.result||!data.media?.before||data.result.target!==job.target)throw new Error("Resultatet saknas.");
      const {evaluateSpecRows}=await import("../local-run/LocalRunPanel");if(cancelled)return;
      const measured=data.media as Media,finished=measured.after||measured.before;
      let evaluated=evaluateSpecRows({label:`Audiobook ${job.target} LUFS`,lufs:job.target,dbtp:-3,brusgolv:-60,lufsTol:.5},measured.before.analysis,finished.analysis,measured.before.noiseFloorDb,finished.noiseFloorDb??Number.NaN,"sv");
      if(job.operation.mode==="validate")evaluated=evaluated.map(row=>({...row,before:"—",outcome:row.parameter==="Signal/brus"?"—":row.outcome}));
      setRows(evaluated);setMedia(measured);setResult(data.result);setSourceId(data.sourceId||job.sourceId||job.id);setPhase("done");setMessage("");setWhole(false);setCurrent(0);pendingSeek.current=0;
      if(job.operation.mode!=="preview"){setOverview(measured.before);setSource(measured.before);}else if(data.sourceUrl&&job.overview){setSource(previous=>previous||{...job.overview!,url:data.sourceUrl});}
      const finishedJob={...job,sourceId:data.sourceId||job.sourceId||job.id,expires:data.expires};setJob(finishedJob);remember(finishedJob);return;
    }
    setMessage(data.status==="queued"?"Din fil står i kö. Du kan lyssna på originalet under tiden.":(data.progress?.replace(/^Provmastrar ditt avsnitt(?:…|\.\.\.)?$/, "Mastrar utdrag"))||"Bearbetar din fil…");
    }catch{if(!cancelled)setMessage("Anslutningen är tillfälligt bruten. Vi försöker igen automatiskt…");}if(!cancelled)timer=setTimeout(poll,3000);};void poll();return()=>{cancelled=true;clearTimeout(timer);};},[job,phase]);
  useEffect(()=>{if(!playing)return;let frame:number;const tick=()=>{const lead=active.current==="before"?a.current:b.current;if(lead)setCurrent(lead.currentTime);if(synced&&a.current&&b.current&&!a.current.seeking&&!b.current.seeking&&Math.abs(a.current.currentTime-b.current.currentTime)>.04)b.current.currentTime=a.current.currentTime;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,synced]);
  async function download(){if(!job)return;const filename=masterFilename(downloadStem);if(!filename){setError("Ange ett filnamn på högst 236 tecken, utan snedstreck eller specialtecken som : och ?. ");return;}setError("");try{const response=await audiobookFetch(endpoint(job.id,"download")+"&filename="+encodeURIComponent(filename)),data=await response.json();if(!response.ok)throw new Error(data.error);const link=document.createElement("a");link.href=data.url;link.download=filename;link.click();}catch(e){setError(e instanceof Error?e.message:"Nedladdningen misslyckades.");}}
  async function report(){if(!job||!media||reportBusy)return;setReportBusy(true);try{const {buildDeliveryReportHtml,downloadBlob}=await import("../local-run/LocalRunPanel");const mode=job.operation.mode,scope=mode==="preview"?`Provmaster ${fmt(job.operation.start)}–${fmt(job.operation.start+media.before.duration)}. Gäller endast valt avsnitt.`:mode==="validate"?"Kontroll av hela originalet. Ingen mastring har utförts.":"Hela ljudboken, före och efter mastring.";
    const html=buildDeliveryReportHtml({filename:job.name,dateLabel:new Date(job.started).toLocaleString("sv-SE"),specLabel:`Audiobook ${job.target} LUFS · ${scope}`,rows:rows as Parameters<typeof buildDeliveryReportHtml>[0]["rows"],locale:"sv",measurementOnly:mode==="validate",methodology:`${scope} FFmpeg loudnorm mäter integrerad LUFS, true peak och LRA. Brusgolv uppskattas från tionde percentilen av RMS-fönster (2048 sampel, steg 512 vid 48 kHz); signal/brus är en indikator baserad på LUFS minus brusgolv. Lyssningen strömmas som MP3, mätvärdena gäller källfilen och eventuell WAV-master. Tekniska mätvärden ersätter inte lyssningskontroll.`});downloadBlob(`${job.name.replace(/\.[^.]+$/,"")}_${mode}_rapport.html`,html);
    }catch{setError("Rapporten kunde inte skapas. Försök igen.");}finally{setReportBusy(false);}}
  const failed=rows.filter(row=>row.status==="fail"),canRun=!!file||!!sourceId;
  return <main className="ab-studio" lang="sv">
    <header className="ab-header"><a href="/tools/audiobook" className="ab-brand">saltwaves<span>®</span></a><span className="ab-badge">EARSELECT · AUDIOBOOK</span></header>
    <div className="ab-heading"><div><p className="ab-eyebrow">PROVLYSSNA · KONTROLLERA · MASTRA</p><h1>Audiobook<span>.</span></h1></div><p>Lyssna på originalet, välj ljudnivå och jämför resultatet. Du kan börja med ett utdrag eller mastra hela boken direkt.</p></div>
    <ol className="ab-steps" aria-label="Så fungerar det"><li><span>1</span><div><strong>Ladda upp och lyssna</strong><p>Välj din fil och lyssna på originalet.</p></div></li><li><span>2</span><div><strong>Välj nivå och mastra</strong><p>Bearbeta ett utdrag eller hela boken.</p></div></li><li><span>3</span><div><strong>Jämför och ladda ner</strong><p>Växla mellan före och efter när mastern är klar.</p></div></li></ol>
    <section className="ab-workspace" aria-label="Ljudbok och provfönster"><div className="ab-filebar"><div><span className="ab-eyebrow">01 · LADDA UPP OCH LYSSNA</span><h2>{name||"Välj din ljudbok"}</h2></div><button className="ab-secondary" disabled={busy} onClick={()=>input.current?.click()}>{name?"Byt fil":"Välj ljudfil"}</button></div>
      <input ref={input} hidden type="file" accept=".wav,.mp3,.m4a,.aiff" onChange={e=>{if(e.target.files?.[0])void choose(e.target.files[0]);e.target.value="";}}/>
      {!overview?<div className="ab-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])void choose(e.dataTransfer.files[0]);}}><div className="ab-drop-icon">↑</div><p>{phase==="loading"?"Läser in vågformen…":"Dra din ljudfil hit"}</p><span>WAV · högst 6 GB / 15 timmar · mono eller stereo<br/>MP3, M4A och AIFF upp till 200 MB</span></div>:<>
        <Wave item={overview} current={whole?current:current+comparisonOffset} title="Hela originalet · vågformsöversikt" onSeek={time=>{if(source)listenWhole(time);else move(time);}} selection={{start,length,disabled:busy,change:move}}/>
        <div className="ab-timeline"><span>0:00:00</span><span>{fmt(overview.duration/2)}</span><span>{fmt(overview.duration)}</span></div>
        <div className="ab-preview-controls"><div><strong>Välj ett utdrag</strong><p>Dra det orange fönstret till det du vill höra, eller ange starttiden.</p></div><label>Starttid <input key={start} aria-label="Utdragets starttid" type="text" inputMode="numeric" placeholder="0:00:00" disabled={busy} defaultValue={fmt(start)} onBlur={e=>{const parts=e.target.value.trim().split(":").map(Number);if(parts.length===3&&parts.every(Number.isFinite)&&parts[0]>=0&&parts[1]>=0&&parts[1]<60&&parts[2]>=0&&parts[2]<60){move(parts[0]*3600+parts[1]*60+parts[2]);setError("");}else{e.target.value=fmt(start);setError("Ange starttiden som timmar:minuter:sekunder, till exempel 1:30:00.");}}} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/><span>timmar:minuter:sekunder</span></label><label>Längd <select aria-label="Utdragets längd" disabled={busy} value={length} onChange={e=>{const value=Number(e.target.value);setLength(value);setStart(Math.min(start,Math.max(0,overview.duration-value)));}}><option value={300}>5 minuter</option><option value={600}>10 minuter</option></select></label><p className="ab-selection-time">Valt: {fmt(start)}–{fmt(Math.min(overview.duration,start+length))}</p></div>
      </>}
      {media&&<div className="ab-listen-tabs"><button className="ab-secondary" disabled={!source} aria-pressed={whole} onClick={()=>listenWhole()}>Hela originalet</button><button className="ab-secondary" aria-pressed={!whole} onClick={listenComparison}>{job?.operation.mode==="preview"?`Mastrat utdrag ${fmt(comparisonOffset)}–${fmt(comparisonOffset+media.before.duration)}`:job?.operation.mode==="validate"?"Kontrollerat original":"Före / efter hela boken"}</button></div>}
      {!whole&&media&&<><Wave item={media.before} current={current} title="Före · Original" onSeek={seek}/>{media.after&&<Wave item={media.after} current={current} title="Efter · Master" onSeek={seek}/>}</>}
      <div className="ab-transport"><div className="ab-buttons"><button className="ab-play" aria-label={playing?"Pausa":"Spela"} disabled={!before?.url} onClick={()=>void play()}>{playing?"Ⅱ":"▶"}</button><button className="ab-stop" aria-label="Stoppa och gå till början" disabled={!before?.url} onClick={()=>stop(true)}>■</button><span className="ab-time">{fmt(current)} <span>/ {fmt(before?.duration||0)}</span></span></div><div className="ab-switch" role="group" aria-label="Jämför före och efter"><button aria-pressed={slot==="before"} onClick={()=>mix("before")}>Före</button><button disabled={!synced} aria-pressed={slot==="after"} onClick={()=>mix("after")}>Efter</button></div></div>
      {!synced&&<p className="ab-after-help" role="status">{!name?"Börja med att välja en ljudfil i steg 1.":media?.after&&whole?"Välj jämförelsen ovan för att lyssna på före och efter.":job?.operation.mode==="validate"&&result?"Originalet är kontrollerat. Mastra ett utdrag eller hela boken för att kunna lyssna på Efter.":busy?"Efter blir tillgängligt när mastringen är klar.":"Du lyssnar på originalet. Välj Mastra ett utdrag eller Mastra hela boken i steg 2 för att kunna lyssna på Efter."}</p>}
      {synced&&<label className="ab-match"><input type="checkbox" checked={matched} onChange={e=>{setMatched(e.target.checked);mix(slot,e.target.checked);}}/>Nivåmatcha lyssningen. Ungefärlig jämförelsenivå; påverkar inte mastern.</label>}
      <audio ref={a} src={before?.url} preload="metadata" crossOrigin="anonymous" onLoadedMetadata={()=>{if(pendingSeek.current!==null&&a.current){a.current.currentTime=Math.min(pendingSeek.current,a.current.duration);pendingSeek.current=null;}}} onEnded={()=>stop(true)}/><audio ref={b} src={after?.url} preload="metadata" crossOrigin="anonymous" onEnded={()=>stop(true)}/>
    </section>
    <section className="ab-master-panel"><div><p className="ab-eyebrow">02 · VÄLJ NIVÅ OCH MASTRA</p><h2>Mål för din ljudbok</h2><p>Välj önskad ljudnivå för din ljudbok.</p></div><div className="ab-targets" role="group" aria-label="Mål LUFS">{[-19,-18,-17,-16].map(value=><button key={value} disabled={busy} aria-pressed={target===value} onClick={()=>setTarget(value)}><strong>−{Math.abs(value)}</strong><span>LUFS</span></button>)}</div></section>
    <section className="ab-actions" aria-label="Bearbetning"><button className="ab-master" disabled={!canRun||busy||!overview} onClick={()=>void run("preview")}>Mastra ett utdrag <span>↗</span></button><button className="ab-secondary" disabled={!canRun||busy} onClick={()=>void run("validate")}>Kontrollera hela filen</button><button className="ab-secondary" disabled={!canRun||busy} onClick={()=>void run("master")}>Mastra hela boken</button><p>Mastra ett utdrag på 5 eller 10 minuter för att lyssna på resultatet innan du bearbetar hela boken. Du kan också mastra hela boken direkt. Kontrollera hela filen mäter originalet utan att ändra ljudet. Slutmastern kan skilja sig från utdraget eftersom hela filens nivå och dynamik bedöms.</p></section>
    <div role="status" aria-live="polite" className="ab-status">{busy&&<><span className="ab-spinner"/>{message}</>}</div>
    {error&&<p role="alert" className="ab-error">{error}</p>}
    {stale&&result&&<p className="ab-info">Fönstret eller LUFS-målet har ändrats. Resultatet nedan gäller fortfarande {fmt(job!.operation.start)} vid {job!.target} LUFS. Tryck Mastra ett utdrag för ett nytt resultat.</p>}
    {!result&&<section className="ab-next-step"><p className="ab-eyebrow">03 · JÄMFÖR OCH LADDA NER</p><h2>Här visas ditt resultat.</h2><p>När mastringen är klar kan du lyssna på före och efter, läsa rapporten och ladda ner ljudfilen.</p></section>}
    {result&&job&&<section className="ab-result"><div><p className="ab-eyebrow">03 · {job.operation.mode==="validate"?"LEVERANSKONTROLL":job.operation.mode==="preview"?"DITT MASTRADE UTDRAG ÄR KLART":"DIN MASTER ÄR KLAR"}</p><h2>{job.operation.mode==="validate"?"Kontroll av originalet.":"Lyssna på skillnaden."}</h2><p>{job.operation.mode==="preview"?`${fmt(job.operation.start)}–${fmt(job.operation.start+(media?.before.duration||0))} · ${job.target} LUFS. Rapporten gäller endast detta avsnitt.`:job.operation.mode==="validate"?"Hela originalfilen har mätts. Ingen mastring har utförts.":`Hela ljudboken · ${job.target} LUFS.`}</p></div>
      <p className={failed.length?"ab-error":"ab-info"}>{failed.length?`Utanför målkraven: ${failed.map(row=>row.parameter).join(", ")}. Granska rapporten och lyssna innan leverans.`:"De uppmätta målkraven klaras. Gör också en lyssningskontroll före leverans."}</p>
      <div className="ab-report-table"><table><thead><tr><th>Parameter</th>{job.operation.mode!=="validate"&&<th>Före</th>}<th>{job.operation.mode==="validate"?"Uppmätt":"Efter"}</th><th>Krav</th><th>Utfall</th></tr></thead><tbody>{rows.map(row=><tr key={row.parameter}><td>{row.parameter}</td>{job.operation.mode!=="validate"&&<td>{row.before}</td>}<td>{row.after}</td><td>{row.requirement}</td><td className={row.status==="fail"?"ab-fail":""}>{row.outcome||(row.status==="pass"?"OK":row.status==="fail"?"Avvikelse":"—")}</td></tr>)}</tbody></table></div>
      {job.operation.mode!=="validate"&&<label className="ab-filename">Filnamn för nedladdning<div><input aria-label="Filnamn för nedladdning" value={downloadStem} maxLength={236} onChange={e=>setDownloadStem(e.target.value)} spellCheck={false}/><span>.wav</span></div><small>Originalets namn är förifyllt. Du kan ändra det här.</small></label>}
      <div className="ab-downloads">{job.operation.mode!=="validate"&&<button className="ab-master" onClick={()=>void download()}>{job.operation.mode==="preview"?"Ladda ner mastrat utdrag":"Ladda ner master"}<span>↓</span></button>}<button className="ab-secondary" disabled={reportBusy} onClick={()=>void report()}>{reportBusy?"Skapar rapport…":"Ladda ner rapport"}</button></div>
    </section>}
    <p className="ab-retention">Uppladdade filer och resultat tas bort automatiskt efter 48 timmar från uppladdningen. {job?.expires?`Tillgängligt till ${new Date(job.expires*1000).toLocaleString("sv-SE")}.`:"Ladda ner det du vill behålla."}</p>
    <footer className="ab-footer"><span>SALTWAVES STUDIO</span><span>En fil. En enhetlig behandling.</span></footer>
  </main>;
}
